[project]
name = "slackbot-poc"
version = "0.1.0"
description = "Slack bot for processing CSV files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "slack-sdk>=3.20.0",
    "pandas>=2.0.0",
    "python-dotenv>=1.0.0",
]
